name: cstutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - astropy>=3.0
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - voila
