name: profiling
channels:
  - defaults
dependencies:
  - graphviz
  - pyqt
  - pip
  - pip:
    - gprof2dot
    - matplotlib
    - memory-profiler
    - numba
    - numpy
    - pyinstrument
    - snakeviz
